In [1]:
print("Hello")

Hello


In [29]:
(t2.timestamp()*1000) % (t3.total_seconds()*1000)

601200000.0

In [18]:
(t3.total_seconds()*1000)

604800000.0

In [32]:
from datetime import datetime, timedelta
t2 = datetime(year=2000,month=10,day=7)
t3 = timedelta(weeks=1)

((t2.timestamp()*1000) % (t3.total_seconds()*1000))/(t3.total_seconds()*1000)

0.27976190476190477

In [12]:
timedelta(milliseconds=1).total_seconds()*1000

1.0

In [36]:
all([True,True,True])

True

In [39]:
from torch import Tensor
import torch

In [93]:
out = torch.ones([2,5,4,6], dtype=torch.float64, device="cpu")

In [60]:
out.shape[:-1] + tuple([1])

torch.Size([5, 4, 1])

In [69]:
len({1,2,3,5,6,6,7,89,0} - {3,5})

6

In [72]:
out[:,:,list({1,0})].shape

torch.Size([5, 4, 2])

In [70]:
list({1,2,3,5,6,6,7,89,0} - {3,5})

[0, 1, 2, 6, 7, 89]

In [86]:
out[:,:,:1] = 0

In [87]:
out

tensor([[[0., 1., 0.],
         [0., 1., 0.],
         [0., 1., 0.],
         [0., 1., 0.]],

        [[0., 1., 0.],
         [0., 1., 0.],
         [0., 1., 0.],
         [0., 1., 0.]],

        [[0., 1., 0.],
         [0., 1., 0.],
         [0., 1., 0.],
         [0., 1., 0.]],

        [[0., 1., 0.],
         [0., 1., 0.],
         [0., 1., 0.],
         [0., 1., 0.]],

        [[0., 1., 0.],
         [0., 1., 0.],
         [0., 1., 0.],
         [0., 1., 0.]]], dtype=torch.float64)

In [1]:
from timefusion import PositionalEncoding
import torch

out = torch.ones([2,5,4,6], dtype=torch.float, device="cpu")

k = PositionalEncoding(6,[],[2,5])

k(out)[0][0][0]

tensor([ 1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00, -2.4493e-16,
        -2.4493e-16,  1.0000e+00,  1.0000e+00,  6.2831e-03,  6.2831e-03,
         9.9998e-01,  9.9998e-01,  1.0472e-04,  1.0472e-04,  1.0000e+00,
         1.0000e+00,  7.2722e-08,  7.2722e-08,  1.0000e+00,  1.0000e+00,
         1.0389e-08,  1.0389e-08,  1.0000e+00,  1.0000e+00,  2.4241e-09,
         2.4241e-09,  1.0000e+00,  1.0000e+00,  1.9924e-10,  1.9924e-10,
         1.0000e+00,  1.0000e+00,  1.9924e-11,  1.9924e-11,  1.0000e+00,
         1.0000e+00], dtype=torch.float64)

In [1]:
from timefusion import Embedding, PositionalEncoding
import torch

out = torch.ones([32,100,100,6], dtype=torch.float, device="cpu")

k0 = PositionalEncoding(6,"cpu",[2],[4],num_sines=20)
k1 = Embedding(k0.encoding_dim,3,"cpu")

out = k0(out)
out = k1(out)

TypeError: '<=' not supported between instances of 'int' and 'str'

In [10]:
sum(p.numel() for p in k0.parameters())

0

In [3]:
torch.backends.mps.is_available()

True

In [8]:
from timefusion import TimeFusion
import torch

context = torch.ones([64,25,30,12], dtype=torch.float, device=torch.device("mps"))
queries = torch.ones([64,25,30,12], dtype=torch.float, device=torch.device("mps"))

k0 = TimeFusion(
    6,
    [1],
    [2],
    d_model=64,
    num_encoder_layers=3,
    num_decoder_layers=3,
    nhead=4,
    device=torch.device("mps")
)


k0(context,queries)

#print("Number of trainable parameters:",sum(p.numel() for p in k0.parameters()))

tensor([[[ 0.3611,  0.0547, -0.2151,  ...,  0.0236, -0.0755,  0.0619],
         [-0.0938,  0.0656,  0.3135,  ...,  0.0928,  0.5036,  0.1467],
         [ 0.3115,  0.0880, -0.0383,  ..., -0.1538,  0.2584, -0.3283],
         ...,
         [ 0.0280,  0.0997, -0.1567,  ...,  0.1825, -0.0126,  0.0458],
         [ 0.1831, -0.0470, -0.1689,  ...,  0.0848, -0.0131,  0.1431],
         [-0.0108, -0.2455,  0.1312,  ...,  0.1036, -0.1174,  0.2445]],

        [[ 0.1422,  0.4056,  0.1905,  ...,  0.0233,  0.0817,  0.0444],
         [ 0.0832, -0.2339,  0.0284,  ..., -0.0694, -0.0855,  0.4663],
         [ 0.0714,  0.3465, -0.0388,  ...,  0.3035, -0.2639,  0.1506],
         ...,
         [ 0.1812,  0.2446, -0.3270,  ...,  0.1910,  0.0325,  0.1923],
         [ 0.2105,  0.2900, -0.5765,  ..., -0.0193,  0.4274, -0.0617],
         [ 0.4102,  0.2106, -0.0867,  ...,  0.1087, -0.0036, -0.0530]],

        [[ 0.2121, -0.0489,  0.0498,  ..., -0.0152,  0.3661, -0.3755],
         [ 0.1209,  0.1677, -0.1360,  ...,  0

In [35]:
import time
import sys

print("edvard")
print()
for x in ["hello","hi"]:
    time.sleep(1)
    #print("\u007F"*128,end="")
    print("\u007F"*512,"\r",x, end="\r")

edvard



In [24]:
"t"*10

'tttttttttt'

In [3]:
out[:,:,:,0].shape

torch.Size([32, 100, 100])

In [ ]:
for p in k0.parameters():
    print(p.numel())

In [2]:
k0(out)

TypeError: TimeFusion.forward() takes 1 positional argument but 2 were given

In [22]:
from timefusion import TimeFusion
import torch

out = torch.ones([32,50,100,6], dtype=torch.float, device="cpu")

out.random_(0,10)

all((torch.flatten(out,start_dim=1,end_dim=2).reshape([32,50,100,6]) == out).flatten())

True

In [23]:
all((torch.flatten(out,start_dim=1,end_dim=2)[:,:,0].reshape([32,50,100]) == out[:,:,:,0]).flatten())

True

In [19]:
out

tensor([[[[1., 0., 8., 7., 1., 0.],
          [2., 2., 2., 0., 0., 9.],
          [9., 3., 1., 5., 4., 0.],
          ...,
          [8., 9., 7., 9., 6., 4.],
          [3., 5., 3., 8., 6., 6.],
          [8., 7., 4., 8., 8., 6.]],

         [[3., 0., 9., 7., 3., 6.],
          [5., 9., 6., 4., 4., 9.],
          [6., 3., 3., 0., 2., 3.],
          ...,
          [2., 6., 0., 9., 6., 0.],
          [1., 7., 2., 4., 6., 1.],
          [6., 9., 7., 0., 8., 0.]],

         [[0., 4., 6., 0., 3., 9.],
          [5., 6., 0., 8., 4., 4.],
          [9., 5., 4., 1., 3., 7.],
          ...,
          [1., 9., 9., 1., 8., 8.],
          [3., 1., 0., 5., 1., 3.],
          [2., 6., 4., 7., 4., 7.]],

         ...,

         [[5., 0., 6., 5., 2., 2.],
          [3., 0., 3., 5., 3., 1.],
          [9., 6., 1., 1., 9., 3.],
          ...,
          [8., 5., 4., 9., 1., 5.],
          [3., 2., 2., 1., 7., 2.],
          [2., 6., 0., 6., 9., 9.]],

         [[2., 1., 2., 5., 4., 8.],
          [5., 4.