In [1]:
print("Hello")

Hello


In [29]:
(t2.timestamp()*1000) % (t3.total_seconds()*1000)

601200000.0

In [18]:
(t3.total_seconds()*1000)

604800000.0

In [32]:
from datetime import datetime, timedelta
t2 = datetime(year=2000,month=10,day=7)
t3 = timedelta(weeks=1)

((t2.timestamp()*1000) % (t3.total_seconds()*1000))/(t3.total_seconds()*1000)

0.27976190476190477

In [12]:
timedelta(milliseconds=1).total_seconds()*1000

1.0

In [36]:
all([True,True,True])

True

In [39]:
from torch import Tensor
import torch

In [93]:
out = torch.ones([2,5,4,6], dtype=torch.float64, device="cpu")

In [60]:
out.shape[:-1] + tuple([1])

torch.Size([5, 4, 1])

In [69]:
len({1,2,3,5,6,6,7,89,0} - {3,5})

6

In [72]:
out[:,:,list({1,0})].shape

torch.Size([5, 4, 2])

In [70]:
list({1,2,3,5,6,6,7,89,0} - {3,5})

[0, 1, 2, 6, 7, 89]

In [86]:
out[:,:,:1] = 0

In [87]:
out

tensor([[[0., 1., 0.],
         [0., 1., 0.],
         [0., 1., 0.],
         [0., 1., 0.]],

        [[0., 1., 0.],
         [0., 1., 0.],
         [0., 1., 0.],
         [0., 1., 0.]],

        [[0., 1., 0.],
         [0., 1., 0.],
         [0., 1., 0.],
         [0., 1., 0.]],

        [[0., 1., 0.],
         [0., 1., 0.],
         [0., 1., 0.],
         [0., 1., 0.]],

        [[0., 1., 0.],
         [0., 1., 0.],
         [0., 1., 0.],
         [0., 1., 0.]]], dtype=torch.float64)

In [1]:
from timefusion import PositionalEncoding
import torch

out = torch.ones([2,5,4,6], dtype=torch.float, device="cpu")

k = PositionalEncoding(6,[],[2,5])

k(out)[0][0][0]

tensor([ 1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00, -2.4493e-16,
        -2.4493e-16,  1.0000e+00,  1.0000e+00,  6.2831e-03,  6.2831e-03,
         9.9998e-01,  9.9998e-01,  1.0472e-04,  1.0472e-04,  1.0000e+00,
         1.0000e+00,  7.2722e-08,  7.2722e-08,  1.0000e+00,  1.0000e+00,
         1.0389e-08,  1.0389e-08,  1.0000e+00,  1.0000e+00,  2.4241e-09,
         2.4241e-09,  1.0000e+00,  1.0000e+00,  1.9924e-10,  1.9924e-10,
         1.0000e+00,  1.0000e+00,  1.9924e-11,  1.9924e-11,  1.0000e+00,
         1.0000e+00], dtype=torch.float64)

In [1]:
from timefusion import Embedding, PositionalEncoding
import torch

out = torch.ones([32,100,100,6], dtype=torch.float, device="cpu")

k0 = PositionalEncoding(6,"cpu",[2],[4],num_sines=20)
k1 = Embedding(k0.encoding_dim,3,"cpu")

out = k0(out)
out = k1(out)

TypeError: '<=' not supported between instances of 'int' and 'str'

In [10]:
sum(p.numel() for p in k0.parameters())

0

In [3]:
torch.backends.mps.is_available()

True

In [2]:
from timefusion import TimeFusion
import torch

context = torch.ones([32,100,30,6], dtype=torch.float, device=torch.device("mps"))
queries = torch.ones([32,100,30,6], dtype=torch.float, device=torch.device("mps"))

k0 = TimeFusion(
    6,
    [1],
    [2],
    d_model=16,
    num_encoder_layers=3,
    num_decoder_layers=3,
    nhead=4,
    device=torch.device("mps")
)

k0(context,queries)

#print("Number of trainable parameters:",sum(p.numel() for p in k0.parameters()))

tensor([[[-1.7064, -1.5153, -1.6143,  ..., -1.4957, -1.4604, -1.5956],
         [-1.3337, -1.5952, -1.4514,  ..., -1.4992, -1.4971, -1.5148],
         [-1.7092, -1.7263, -1.4375,  ..., -1.8299, -1.4984, -1.4911],
         ...,
         [-1.4072, -1.6641, -1.7351,  ..., -1.6699, -1.8084, -1.4696],
         [-1.5174, -1.7515, -1.5336,  ..., -1.4461, -1.6789, -1.0587],
         [-1.7994, -1.3123, -1.6555,  ..., -1.7759, -1.8222, -1.4347]],

        [[-1.6476, -1.5991, -1.6669,  ..., -1.7333, -1.7224, -1.6762],
         [-1.3739, -1.7206, -1.5738,  ..., -1.5877, -1.4844, -1.4666],
         [-1.7550, -1.8126, -1.4560,  ..., -1.1913, -1.7262, -1.5442],
         ...,
         [-1.5775, -1.7211, -1.7374,  ..., -1.6274, -1.6388, -1.7676],
         [-1.2962, -1.6645, -1.6026,  ..., -1.6961, -1.5600, -1.4352],
         [-1.6964, -1.5579, -1.8554,  ..., -1.6517, -1.6468, -1.8127]]],
       device='mps:0', grad_fn=<ReshapeAliasBackward0>)

In [3]:
out[:,:,:,0].shape

torch.Size([32, 100, 100])

In [ ]:
for p in k0.parameters():
    print(p.numel())

In [2]:
k0(out)

TypeError: TimeFusion.forward() takes 1 positional argument but 2 were given

In [22]:
from timefusion import TimeFusion
import torch

out = torch.ones([32,50,100,6], dtype=torch.float, device="cpu")

out.random_(0,10)

all((torch.flatten(out,start_dim=1,end_dim=2).reshape([32,50,100,6]) == out).flatten())

True

In [23]:
all((torch.flatten(out,start_dim=1,end_dim=2)[:,:,0].reshape([32,50,100]) == out[:,:,:,0]).flatten())

True

In [19]:
out

tensor([[[[1., 0., 8., 7., 1., 0.],
          [2., 2., 2., 0., 0., 9.],
          [9., 3., 1., 5., 4., 0.],
          ...,
          [8., 9., 7., 9., 6., 4.],
          [3., 5., 3., 8., 6., 6.],
          [8., 7., 4., 8., 8., 6.]],

         [[3., 0., 9., 7., 3., 6.],
          [5., 9., 6., 4., 4., 9.],
          [6., 3., 3., 0., 2., 3.],
          ...,
          [2., 6., 0., 9., 6., 0.],
          [1., 7., 2., 4., 6., 1.],
          [6., 9., 7., 0., 8., 0.]],

         [[0., 4., 6., 0., 3., 9.],
          [5., 6., 0., 8., 4., 4.],
          [9., 5., 4., 1., 3., 7.],
          ...,
          [1., 9., 9., 1., 8., 8.],
          [3., 1., 0., 5., 1., 3.],
          [2., 6., 4., 7., 4., 7.]],

         ...,

         [[5., 0., 6., 5., 2., 2.],
          [3., 0., 3., 5., 3., 1.],
          [9., 6., 1., 1., 9., 3.],
          ...,
          [8., 5., 4., 9., 1., 5.],
          [3., 2., 2., 1., 7., 2.],
          [2., 6., 0., 6., 9., 9.]],

         [[2., 1., 2., 5., 4., 8.],
          [5., 4.